/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubes.pbo;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.*;

/**
 *
 * @author Harits Rahman
 */
public class Forza extends javax.swing.JFrame {

    /**
     * Creates new form Forza
     */
    public Forza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("VCR OSD Mono", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harits Rahman\\Downloads\\Forza_Horizon_5_cover_art.jpg")); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Your Ultimate Horizon Adventure awaits! Explore the vibrant and \never-evolving open world landscapes of Mexico with limitless, \nfun driving action in hundreds of the world’s greatest cars.\nTake on awe-inspiring weather events such as towering dust storms \nand intense tropical storms as Mexico’s unique, dynamic seasons change\nthe world every week. Keep coming back for new events, challenges,\ncollectibles, and rewards, and new areas to explore. No two seasons\nwill ever be the same.");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Recent Reviews : Very Positive\nRelease Date : 9 November 2021\nDeveloper : Playground Games\nPublisher : Xbox Game Studios\nGenre : Racing, Open World");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("System Minimum Requirement\nGPU :\nGTX 16 series\nCPU :\nIntel core i5\nRAM :\n16GB\nStorage :\n110GB space available");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(0, 153, 153));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("VCR OSD Mono", 0, 12)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText("Tell us the\nspecification of\nyour device\n\nso we can you\nwhether you can run\nthis game or not");
        jTextArea4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setViewportView(jTextArea4);

        jLabel6.setFont(new java.awt.Font("VCR OSD Mono", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FORZA HORIZON 5");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harits Rahman\\Downloads\\tumblr_481bfe8a7083ee036a32fd07735346d3_3744ab1e_540.gif")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("VCR OSD Mono", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GPU");

        gpulist.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        gpulist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTX9 series", "GTX10 series", "GTX16 series", "RTX20 series", "RTX30 series" }));
        gpulist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpulistActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("VCR OSD Mono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPU");

        cpulist.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        cpulist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "intel core i3", "intel core i5", "intel core i7", "intel core i9", "amd ryzen3", "amd ryzen5", "amd ryzen7", "amd ryzen9" }));
        cpulist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpulistActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("VCR OSD Mono", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RAM");

        ramlist.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        ramlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2GB", "4GB", "8GB", "16GB", "32GB" }));
        ramlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramlistActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("VCR OSD Mono", 1, 18)); // NOI18N
        jButton3.setText("CHECK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cpulist, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpulist, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addComponent(jButton3))
                            .addComponent(jLabel7)
                            .addComponent(ramlist, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpulist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpulist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ramlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Page4 p4 = new Page4();
        p4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea2PropertyChange

    private void gpulistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpulistActionPerformed
        // TODO add your handling code here:
        int gpu = gpulist.getSelectedIndex();
    }//GEN-LAST:event_gpulistActionPerformed

    private void cpulistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpulistActionPerformed
        // TODO add your handling code here:
        int cpu = cpulist.getSelectedIndex();
    }//GEN-LAST:event_cpulistActionPerformed

    private void ramlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramlistActionPerformed
        // TODO add your handling code here:
        int ram = ramlist.getSelectedIndex();
    }//GEN-LAST:event_ramlistActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int gpu = gpulist.getSelectedIndex();
        int cpu = cpulist.getSelectedIndex();
        int ram = ramlist.getSelectedIndex();

        if(gpu==0&&cpu==0&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==0&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==0&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU), Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//3

        else if(gpu==0&&cpu==0&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==0&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu==4&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==4&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==0&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu==0&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2

        else if(gpu==0&&cpu!=0&&ram==0){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram==0){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram==0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram==1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram==2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram==1){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram==2){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=0&&ram==2){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=0&&ram==1){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) and memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2

        else if(gpu!=0&&cpu==0&&ram==0){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram==0){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram==0){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram==0){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram==1){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram==1){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram==2){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram==2){
            JOptionPane.showMessageDialog(this,"your Processor(CPU),and memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram==1){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram==2){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==0&&ram==2){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==0&&ram==1){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) and RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2

        else if(gpu==0&&cpu!=0&&ram!=0){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram!=0){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=0&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==1&&cpu!=4&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram!=1){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=4&&ram!=2){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=0&&ram!=2){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu==0&&cpu!=0&&ram!=1){
            JOptionPane.showMessageDialog(this,"Your Graphic card(GPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2

        else if(gpu!=0&&cpu==0&&ram!=0){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram!=0){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram!=0){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram!=1){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==0&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu==4&&ram!=2){
            JOptionPane.showMessageDialog(this,"your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram!=1){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==4&&ram!=2){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==0&&ram!=2){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu==0&&ram!=1){
            JOptionPane.showMessageDialog(this,"Your Processor(CPU) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2

        else if(gpu!=0&&cpu!=0&&ram==0){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu!=4&&ram==0){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=0&&ram==0){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=4&&ram==0){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=0&&ram==1){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=4&&ram==1){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=0&&ram==2){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=1&&cpu!=4&&ram==2){
            JOptionPane.showMessageDialog(this,"your memory RAM did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu!=4&&ram==1){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu!=4&&ram==2){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu!=0&&ram==2){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }
        else if(gpu!=0&&cpu!=0&&ram==1){
            JOptionPane.showMessageDialog(this,"Your RAM memory (RAM) did not meet the requirement", "CHECK",JOptionPane.ERROR_MESSAGE);
        }//2
        else{
            JOptionPane.showMessageDialog(this,"Your Device is good to go!", "CHECK",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JComboBox<String> cpulist = new javax.swing.JComboBox<>();
    public static final javax.swing.JComboBox<String> gpulist = new javax.swing.JComboBox<>();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    public static final javax.swing.JComboBox<String> ramlist = new javax.swing.JComboBox<>();
    // End of variables declaration//GEN-END:variables
}
